### ISSUE TITLE
HTMLVideoElement object could not be cloned.

### ISSUE THREAD

**Issue by pittQ** [oct16/TimeCat#129]
- [x] I have searched the [issues](https://github.com/oct16/TimeCat/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://oct16.github.io/timecat-issue-helper/](https://oct16.github.io/timecat-issue-helper/)

### Steps to reproduce
idb.ts?c89a:122 Uncaught (in promise) DOMException: Failed to execute 'add' on 'IDBObjectStore': HTMLVideoElement object could not be cloned.
    at IDB._callee9$ (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:1667:29)
    at tryCatch (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:65:2404)
    at Generator.eval [as _invoke] (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:65:1964)
    at Generator.eval [as next] (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:65:3255)
    at eval (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:133:67)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:112:10)
    at IDB.execAddTask (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:1660:14)
    at IDB.execTask (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:1636:23)
    at eval (webpack-internal:///./node_modules/timecatjs/dist/timecat.esm.js:1491:29)

### What is actually happening?
视频无法录制
视频是跟例子一样,url是加密了的,播放的blob

**Comment by cbbfcd** [comment]
可以提供一个复现的 demo 不
